version: '3.7'

services:
  nginx:
    build:
      args:
        VERSION: $NGINX_VERSION
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: dev
    depends_on:
      - php-fpm
    ports:
      - 8088:80

  php-fpm:
    build:
      args:
        VERSION: $PHP_VERSION
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: dev
    volumes:
      - .:/app
